-- Create the table for contact messages
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.contact_messages enable row level security;

-- Create policy to allow anyone (anon) to insert messages
create policy "Enable insert for everyone" on public.contact_messages
  for insert with check (true);

-- Create policy to allow public read access (for admin page demo)
-- WARNING: In a production app, you should use authenticated roles.
create policy "Enable read access for everyone" on public.contact_messages
  for select using (true);
